# Generated by Django 3.0.8 on 2020-09-11 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('food_or_travel', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurentOrPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='Location')),
                ('restaurent_place', models.CharField(choices=[('Restaurent', 'Restaurent'), ('Place', 'Place')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=100, verbose_name='Title')),
                ('review_body', models.TextField()),
                ('is_offer_or_planned', models.BooleanField(verbose_name='Offered or planned')),
                ('is_recommended', models.BooleanField(verbose_name='Recommended')),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_or_discussion', models.CharField(max_length=20, null=None)),
                ('food_or_travel', models.CharField(max_length=20, verbose_name='Foods or Travel')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='reviews.Item')),
                ('restaurentOrPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.RestaurentOrPlace')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('foods_or_travel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.FloatField(verbose_name='Food')),
                ('environment', models.FloatField(verbose_name='Food')),
                ('service', models.FloatField(verbose_name='Food')),
                ('cleanliness', models.FloatField(verbose_name='Food')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Review')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(to='reviews.Tag'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
                ('is_disliked', models.BooleanField(default=False)),
                ('is_helpful', models.BooleanField(default=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Review')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reviews.models.get_image_name, verbose_name='Image')),
                ('review', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reviews.Review')),
            ],
        ),
    ]
